name: Train model
desc: tired
cmd: python stub.py --data "${DATA}" --model "${MODEL}"
env:
  python:
    type: manual
    version: 3.10
    requirements-file: requirements.txt
    local-paths:
      - pipeline2.py
      - stub.py
inputs:
  - vprod_train.zip: DATA
outputs:
  - model.pt: MODEL
cloud-instance-type: g1.1
